services:
  - type: web
    name: rails-mobi-web
    env: ruby
    plan: free
    numInstances: 1
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/deploy/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-mobi-db
          property: connectionString 
      - key: RAILS_MASTER_KEY
        sync: false


databases:
  - name: rails-mobi-db
    plan: free
    postgresMajorVersion: 14